### ISSUE TITLE
csperf crashes when open files are less than max connections

### ISSUE THREAD

**Issue by niks3089** [niks3089/csperf#41]
```
[root@localhost csperf]# csperf -c 10.1.1.135 -C 2000 -P 600
Starting test. Please wait...
10% completed...
20% completed...
30% completed...
40% completed...
50% completed...
60% completed...
70% completed...
80% completed...
90% completed...
100% completed...
Test summary
-------------
Total connections attempted: 1997
Total connections connected: 0
Total connects failed: 2000
Total connection errors: 0
Total data sent: 0 B
Total data received: 0 B
Total blocks sent: 0
Total blocks received: 0
Total commands sent: 0
Total commands received: 0
Total time taken: 409.000 ms

Detailed test summary can be found in csperf_client_out.txt file
Segmentation fault (core dumped)
```

```
#0  0x000000000040cb56 in csperf_client_manager_setup_clients (cli_mgr=0x2ac36c4df010, total_clients=1) at /root/csperf/src/csperf_client.c:632
#1  0x000000000040ba64 in csperf_client_shutdown (client=0x2ac36c5095e8, ignore=0) at /root/csperf/src/csperf_client.c:175
#2  0x000000000040c813 in csperf_client_eventcb (bev=0x11841f70, events=32, ctx=0x2ac36c5095e8) at /root/csperf/src/csperf_client.c:562
#3  0x000000000041a252 in bufferevent_socket_connect (bev=0x11841f70, sa=<value optimized out>, socklen=16) at /root/csperf/packages/libevent-2.0.21-stable/bufferevent_sock.c:428
#4  0x000000000041a30f in bufferevent_connect_getaddrinfo_cb (result=0, ai=0x118422e0, arg=<value optimized out>) at /root/csperf/packages/libevent-2.0.21-stable/bufferevent_sock.c:461
#5  0x00000000004201f9 in evutil_getaddrinfo_async (dns_base=<value optimized out>, nodename=<value optimized out>, servname=<value optimized out>, hints_in=<value optimized out>, cb=0x41a270 <bufferevent_connect_getaddrinfo_cb>, arg=0x11841f70)
    at /root/csperf/packages/libevent-2.0.21-stable/evutil.c:1421
#6  0x000000000041a09d in bufferevent_socket_connect_hostname (bev=0x11841f70, evdns_base=0x0, family=2, hostname=0x11755f60 "P\006u\021", port=5001) at /root/csperf/packages/libevent-2.0.21-stable/bufferevent_sock.c:497
#7  0x000000000040caf3 in csperf_client_manager_setup_clients (cli_mgr=0x2ac36c4df010, total_clients=1) at /root/csperf/src/csperf_client.c:624
#8  0x000000000040ba64 in csperf_client_shutdown (client=0x2ac36c509430, ignore=0) at /root/csperf/src/csperf_client.c:175
#9  0x000000000040c813 in csperf_client_eventcb (bev=0x11841bb0, events=32, ctx=0x2ac36c509430) at /root/csperf/src/csperf_client.c:562
#10 0x000000000041a252 in bufferevent_socket_connect (bev=0x11841bb0, sa=<value optimized out>, socklen=16) at /root/csperf/packages/libevent-2.0.21-stable/bufferevent_sock.c:428
#11 0x000000000041a30f in bufferevent_connect_getaddrinfo_cb (result=0, ai=0x11841f20, arg=<value optimized out>) at /root/csperf/packages/libevent-2.0.21-stable/bufferevent_sock.c:461
#12 0x00000000004201f9 in evutil_getaddrinfo_async (dns_base=<value optimized out>, nodename=<value optimized out>, servname=<value optimized out>, hints_in=<value optimized out>, cb=0x41a270 <bufferevent_connect_getaddrinfo_cb>, arg=0x11841bb0)
```

**Comment by niks3089** [comment]
```
[root@localhost csperf]# csperf -c 10.1.1.135 -C 1000 -P 200
Starting test. Please wait...
10% completed...
20% completed...
30% completed...
40% completed...
50% completed...
60% completed...
70% completed...
80% completed...
90% completed...
100% completed...
Test summary
-------------
Total connections attempted: 992
Total connections connected: 943
Total connects failed: 207
Total connection errors: 0
Total data sent: 950.367 MB
Total data received: 0 B
Total blocks sent: 943
Total blocks received: 0
Total commands sent: 943
Total commands received: 943
Total time taken: 4.857 s

Detailed test summary can be found in csperf_client_out.txt file
Segmentation fault (core dumped)
[root@localhost csperf]# vi csperf_client_out.txt
```
